'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {Preferences,Toolchain,PICProject,PromptReader,MDBSession,IDECore,CommandRunner,digest,quoteMDB,inside}=require('../core.cjs');
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'aster-test-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const root=path.join(dir,'Example.X');fs.cpSync(path.resolve(__dirname,'../../Examples/FirstLight.X'),root,{recursive:true,filter:p=>!/(^|[\\/])(build|dist)([\\/]|$)/.test(p)});const prefs=new Preferences(path.join(dir,'prefs.json'));return {dir,root,prefs};}
test('opens MPLAB metadata, preserves clock, discovers extra source and restores empty watches',t=>{const {root,prefs}=fixture(t);const p=new PICProject(root,prefs);assert.equal(p.info().configuration,'default');assert(p.clockMHz>=.001&&p.clockMHz<=64);fs.mkdirSync(path.join(root,'nested'));fs.writeFileSync(path.join(root,'nested','extra.asm'),'nop');fs.mkdirSync(path.join(root,'dist'));fs.writeFileSync(path.join(root,'dist','hidden.asm'),'nop');assert(p.info().files.some(f=>f.name==='extra.asm'));assert(!p.info().files.some(f=>f.name==='hidden.asm'));p.saveWatches(['LATD','LATD']);assert.deepEqual(new PICProject(root,prefs).info().watches,['LATD']);p.saveWatches([]);assert.deepEqual(new PICProject(root,prefs).info().watches,[]);});
test('save protects external edits, encodings, generated files and outside paths',t=>{const {root,prefs,dir}=fixture(t);const p=new PICProject(root,prefs);const file=path.join(root,'main.asm'),original=p.read(file);fs.appendFileSync(file,'; external edit');assert.throws(()=>p.save(file,'nop',original.digest,'utf8'),/changed on disk/);const current=p.read(file);p.save(file,'nop\r\n',current.digest,'utf8');assert.equal(fs.readFileSync(file,'utf8'),'nop\r\n');fs.writeFileSync(file,Buffer.from([59,32,233]));const latin=p.read(file);assert.equal(latin.encoding,'latin1');assert.throws(()=>p.save(file,'😀',latin.digest,'latin1'),/Latin-1/);p.save(file,'; é',latin.digest,'latin1');assert.deepEqual(fs.readFileSync(file),Buffer.from([59,32,233]));assert.throws(()=>p.save(path.join(root,'nbproject/configurations.xml'),'x','x','utf8'),/read-only/);const outside=path.join(dir,'outside.asm');fs.writeFileSync(outside,'nop');assert.throws(()=>p.read(outside),/outside/);assert(!inside(root,root+'-other/main.asm'));});
test('rejects generated symlinks escaping the project', {skip:process.platform==='win32'},t=>{const {root,prefs,dir}=fixture(t);const p=new PICProject(root,prefs);fs.mkdirSync(path.join(root,'dist'));const outside=path.join(dir,'outside.asm');fs.writeFileSync(outside,'secret');fs.symlinkSync(outside,path.join(root,'dist','escape.asm'));assert.throws(()=>p.read(path.join(root,'dist','escape.asm')),/outside/);});
test('MDB prompt parser distinguishes chunked confirmations and ignores inline >',()=>{const reader=new PromptReader();assert.deepEqual(reader.receive('value > zero\n  >'),[{ready:true}]);assert.deepEqual(reader.receive('Confirm device\nContinue?\r\n'),[]);assert.deepEqual(reader.receive('>'),[{confirmation:'Confirm device\nContinue?'}]);assert.deepEqual(reader.receive('Done\n>'),[{ready:true}]);assert.throws(()=>quoteMDB('a\nquit'),/one line/);assert.equal(quoteMDB('C:\\My Project\\main.elf'),'"C:/My Project/main.elf"');});
test('toolchain discovers Windows GNU make, bundled Java and handles installation spaces',t=>{const {dir}=fixture(t);const mplab=path.join(dir,'Program Files','Microchip','MPLABX','v6.20'),xc8=path.join(dir,'Program Files','Microchip','xc8','v2.46');for(const f of ['gnuBins/GnuWin32/bin/make.exe','mplab_platform/lib/mdb.jar','sys/java/jre-test/bin/java.exe','packs/Microchip/PIC18F-K_DFP/1.13.292/pack.xml']){fs.mkdirSync(path.dirname(path.join(mplab,f)),{recursive:true});fs.writeFileSync(path.join(mplab,f),'');}fs.mkdirSync(path.join(xc8,'pic-as/bin'),{recursive:true});fs.writeFileSync(path.join(xc8,'pic-as/bin/pic-as.exe'),'');const tc=new Toolchain(mplab,xc8);assert(tc.status().every(s=>s.available));assert(tc.make.endsWith('gnuBins/GnuWin32/bin/make.exe'));assert(tc.java.endsWith('jre-test/bin/java.exe'));assert(Object.keys(tc.environment).filter(k=>k.toLowerCase()==='path').length===1);});
test('real process protocol waits for device confirmation and cancels without issuing another command',async t=>{const {dir}=fixture(t);const fake=path.join(dir,'mdb.cjs');fs.writeFileSync(fake,`process.stdout.write('Ready\\n>');let waiting=false;require('readline').createInterface({input:process.stdin}).on('line',s=>{if(s==='program'){waiting=true;process.stdout.write('Verify voltage?\\n>');}else if(waiting&&s==='yes'){waiting=false;process.stdout.write('Program succeeded.\\n>');}else process.stdout.write(s+' OK\\n>');});`);let confirmations=0;const s=new MDBSession(new Toolchain(),()=>{},async()=>{confirmations++;return true;},()=>{});t.after(()=>s.stop());await s.start(process.execPath,[fake]);assert.match(await s.checked('program'),/Program succeeded/);assert.equal(confirmations,1);assert.equal(await s.checked('next'),'next OK');s.stop();const cancelled=new MDBSession(new Toolchain(),()=>{},async()=>false,()=>{});await cancelled.start(process.execPath,[fake]);await assert.rejects(cancelled.checked('program'),/cancelled/);assert.equal(cancelled.process,null);});
test('runner does not execute shell metacharacters in file arguments',async t=>{const {dir}=fixture(t);const runner=new CommandRunner();const malicious='path & echo unsafe';const r=await runner.run(process.execPath,['-e','process.stdout.write(process.argv[1])',malicious],{cwd:dir});assert.equal(r.code,0);assert.equal(r.log,malicious);});
test('PICkit programming disables probe power and requires explicit success',async t=>{const {root,prefs}=fixture(t);const core=new IDECore(prefs,()=>{},async()=>true);core.open(root);const hex=path.join(root,'dist/default/production/example.hex');fs.mkdirSync(path.dirname(hex),{recursive:true});fs.writeFileSync(hex,':00000001FF');core.build=async()=>({ok:true});const commands=[];let stopped=false;core.newSession=async()=>({checked:async cmd=>{commands.push(cmd);return cmd.startsWith('program ')?'Program succeeded.':'OK';},stop:()=>{stopped=true;}});assert((await core.program(2)).ok);assert(commands.indexOf('set poweroptions.powerenable false')<commands.indexOf('hwtool PICkit3 -p 2'));assert(stopped);core.newSession=async()=>({checked:async()=> 'OK',stop:()=>{}});await assert.rejects(core.program(),/not confirmed/);});
test('breakpoint intentions survive a stop while debugger identifiers are cleared',async t=>{const {root,prefs}=fixture(t);const core=new IDECore(prefs,()=>{},async()=>true);core.open(root);await core.breakpoint(path.join(root,'main.asm'),10);core.breakpoints[0].id=4;core.debugger={stop(){}};await core.debugAction('stop');assert.equal(core.breakpoints.length,1);assert.equal(core.breakpoints[0].id,undefined);await core.breakpoint(path.join(root,'main.asm'),10);assert.equal(core.breakpoints.length,0);});
