'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], E=window.AsterEditor;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={folder:'M3 6h6l2 2h10v11H3z M3 6V4h6l2 2',files:'M8 3h10l3 3v14H8z M8 7H4v14 M17 3v5h4',search:'M16 16l5 5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',chip:'M6 6h12v12H6z M9 9h6v6H9z M9 2v4 M15 2v4 M9 18v4 M15 18v4 M2 9h4 M2 15h4 M18 9h4 M18 15h4',sliders:'M4 3v7 M4 14v7 M12 3v11 M12 18v3 M20 3v3 M20 10v11 M1 10h6v4H1z M9 14h6v4H9z M17 6h6v4h-6z',book:'M12 5C8 2 4 3 2 4v15c4-2 7-1 10 1 3-2 6-3 10-1V4c-4-2-7-1-10 1z M12 5v15',settings:'M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1z M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0',play:'M8 4l12 8-12 8z',pause:'M7 4v16 M17 4v16',stop:'M6 6h12v12H6z',step:'M4 5h6v7h9 M15 8l4 4-4 4 M5 19h14',stepOver:'M3 10a8 8 0 0 1 16-2 M16 4l4 4-4 4 M10 17h4 M12 15v4',reset:'M4 10a8 8 0 1 1 0 5 M4 4v6h6',refresh:'M4 10a8 8 0 0 1 14-5l2 3 M20 3v5h-5 M20 14a8 8 0 0 1-14 5l-2-3 M4 21v-5h5',save:'M4 3h13l4 4v14H3V3z M7 3v6h10V3 M7 21v-8h10v8',clean:'M8 3h8 M4 6h16 M6 6l1 15h10l1-15 M10 10v7 M14 10v7',hammer:'M14 3l7 7-3 3-3-3-9 11-3-3 10-10-2-2z',upload:'M12 16V3 M7 8l5-5 5 5 M4 16v5h16v-5',shield:'M12 2l8 3v6c0 5-5 9-8 11-3-2-8-6-8-11V5z M8 12l3 3 5-6',check:'M5 12l4 4L19 6',arrow:'M5 12h14 M14 7l5 5-5 5',terminal:'M3 5h18v14H3z M6 9l3 3-3 3 M12 15h5'};
function icon(name){return `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.files}"/></svg>`;}
function icons(root=document){root.querySelectorAll('[data-icon]').forEach(el=>{el.innerHTML=icon(el.dataset.icon);});}
icons();
let seq=0,pending=new Map();
function api(op,args={}){return new Promise((resolve,reject)=>{const id=String(++seq);pending.set(id,{resolve,reject});if(!window.webkit?.messageHandlers?.aster){pending.delete(id);reject(Error('Open Aster.app to connect to your local tools.'));return;}window.webkit.messageHandlers.aster.postMessage({id,op,args});});}
window.asterResponse=(id,value,error)=>{const p=pending.get(id);if(!p)return;pending.delete(id);error?p.reject(Error(error)):p.resolve(value);};
let S={project:null,files:new Map(),active:null,view:'files',panel:'output',busy:false,debug:'disconnected',location:{},values:{},previous:{},watches:['TRISD','LATD','PORTD','count'],breakpoints:[],stopwatch:null,diagnostics:[],output:'',debugOutput:'',serialOutput:'',memoryOutput:'',ports:[],serial:false,baud:19200,port:'',recent:[],device:{registers:[],configs:[],pins:[]},tools:[],details:null};
let toastTimer;
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.classList.toggle('error',error);el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,error?10000:4200);}
function log(text){S.output=(S.output+text).slice(-300000);if(S.panel==='output')renderPanel();}
async function task(label,fn){if(S.busy){toast('An operation is already in progress.');return;}S.busy=true;$('#panelStatus').textContent=label;$('#buildStatus').textContent=label;$('#buildStatus').className='working';controls();try{return await fn();}catch(e){toast(e.message,true);$('#buildStatus').textContent='Needs attention';$('#buildStatus').className='bad';log('\n'+e.message+'\n');}finally{S.busy=false;$('#cancelBuild').hidden=true;$('#panelStatus').textContent=S.debug==='disconnected'?'Ready':S.debug==='running'?'Running':'Paused';controls();}}
function stopwatchClock(){const input=$('#stopwatchClock'),value=Number(input.value);if(!Number.isFinite(value)||value<0.001||value>64)throw Error('Enter an oscillator frequency from 0.001 to 64 MHz.');return value;}
function renderStopwatch(){
 const connected=S.debug!=='disconnected',sim=$('#debugTarget').value==='SIM',reading=connected&&sim?S.stopwatch:null;
 $('#resetStopwatch').disabled=!sim||S.debug!=='paused'||S.busy;
 $('#stopwatchClock').disabled=connected||S.busy;$('#stopwatchAccumulate').disabled=connected||S.busy;
 const clock=Number($('#stopwatchClock').value),projectClock=Number(S.project?.clockMHz);$('#stopwatchClockInfo').textContent=Number.isFinite(clock)&&clock>0?(clock/4).toLocaleString(undefined,{maximumFractionDigits:6})+' MHz instruction clock · '+(clock===projectClock?'from project':'override'):'Enter a valid clock frequency.';
 if(reading?.available){const t=reading.seconds,scale=t<.000001?1e9:t<.001?1e6:t<1?1e3:1,unit=scale===1e9?'ns':scale===1e6?'µs':scale===1e3?'ms':'s';$('#stopwatchTime').textContent=reading.elapsedText||(t*scale).toLocaleString(undefined,{maximumFractionDigits:3})+' '+unit;$('#stopwatchCycles').textContent=BigInt(reading.cycles).toLocaleString()+' instruction cycles';}
 else{$('#stopwatchTime').textContent='—';$('#stopwatchCycles').textContent='— instruction cycles';}
 $('#stopwatchHint').textContent=!sim?'Cycle stopwatch is available in Simulator.':!connected?'Clock follows the selected MPLAB configuration.':S.debug==='running'?'Running · updates when paused.':reading?.error?'Stopwatch unavailable: '+reading.error:$('#stopwatchAccumulate').checked?'Since stopwatch reset · paused time is excluded.':'Last run · resets on Continue.';
}
function controls(){renderStopwatch();const has=!!S.project,debug=S.debug!=='disconnected',paused=S.debug==='paused';$('#buildButton').disabled=!has||S.busy||debug||S.project?.prebuilt;$('#cleanButton').disabled=$('#buildButton').disabled;$('#debugButton').disabled=!has||S.busy||debug;$('#programButton').disabled=!has||S.busy||debug;$('#saveButton').disabled=!S.active||S.busy||debug;$('#debugTarget').disabled=S.busy||debug;$('#configuration').disabled=S.busy||debug;$$('[data-debug]').forEach(b=>b.disabled=!debug||S.busy||(b.dataset.debug==='halt'?! (S.debug==='running'):b.dataset.debug!=='stop'&&!paused));$('#refreshRegisters').disabled=!paused||S.busy;$('#refreshStack').disabled=!paused||S.busy;$('#debugState').textContent=debug?S.debug.toUpperCase():'INACTIVE';$('#debugState').className='pill '+(debug?S.debug:'');if(S.active)E.readOnly(debug||S.files.get(S.active)?.readOnly||false);}
function panel(name){S.panel=name;$$('[data-panel]').forEach(el=>el.classList.toggle('active',el.dataset.panel===name));renderPanel();}
function sourceFiles(){return (S.project?.files||[]).filter(f=>/\.(asm|s|S|c|h|inc|cpp)$/.test(f.path));}
function fileIcon(path){const ext=path.split('.').pop().toLowerCase();return `<span class="file-icon ${esc(ext)}">${ext==='asm'||ext==='s'?'A':ext==='c'?'C':ext==='hex'?'⬡':ext==='xml'?'‹›':'≡'}</span>`;}
function renderSidebar(){const body=$('#sidebarBody');$('#sidebarTitle').textContent={files:'EXPLORER',search:'SEARCH',device:'DEVICE',config:'CONFIGURATION',reference:'REFERENCE'}[S.view];
 if(S.view==='files'){
  if(!S.project){body.innerHTML=`<div class="source-tag">Open your MPLAB project to begin. Your source files and build outputs will appear here.</div><div class="tree-heading">RECENT PROJECTS</div>${S.recent.slice(0,8).map((p,i)=>`<button class="file-row" data-recent="${i}">${icon('folder')}<span class="name">${esc(p.split('/').pop())}</span></button>`).join('')}`;body.querySelectorAll('[data-recent]').forEach(b=>b.onclick=()=>openProject(S.recent[+b.dataset.recent]));return;}
  const source=sourceFiles(),other=S.project.files.filter(f=>!source.includes(f));
  const rows=files=>files.map(f=>`<button class="file-row ${S.active===f.path?'active':''}" data-path="${esc(f.path)}" title="${esc(f.path)}">${fileIcon(f.path)}<span class="name">${esc(f.name)}</span>${S.files.get(f.path)?.dirty?'<small>●</small>':''}</button>`).join('');
  body.innerHTML=`<div class="tree-heading">⌄ &nbsp; ${esc(S.project.name.toUpperCase())}<span class="count">.X</span></div><div class="tree-heading">⌄ &nbsp; Source files <span class="muted">${source.length}</span></div>${rows(source)}<div class="tree-separator"></div><div class="tree-heading">⌄ &nbsp; Project</div>${rows(other)}<div class="tree-separator"></div><div class="tree-heading">⌄ &nbsp; Build outputs <span class="count">${S.project.outputs.length}</span></div>${rows(S.project.outputs.filter(f=>/\.(hex|elf|map|lst|sym)$/.test(f.path)))}${S.project.outputs.length?'':'<div class="source-tag">Your HEX, ELF, and map files appear after a successful build.</div>'}`;
  body.querySelectorAll('[data-path]').forEach(b=>b.onclick=()=>safeOpen(b.dataset.path));
 }else if(S.view==='search'){body.innerHTML='<div class="side-search"><input id="projectSearch" class="input small" placeholder="Search source files…" aria-label="Search source files"></div><div id="searchResults" class="source-tag" style="padding-top:16px">Search the current project’s source files.</div>';let timer;$('#projectSearch').oninput=e=>{clearTimeout(timer);timer=setTimeout(()=>projectSearch(e.target.value),250);};$('#projectSearch').focus();
 }else if(S.view==='device'){body.innerHTML=`<div class="tree-heading">PIC18F87K22</div><button class="file-row" id="showRegisters">${icon('chip')} Registers & bit fields</button><button class="file-row" id="showPins">${icon('sliders')} 80-pin package</button><div class="tree-separator"></div><div class="source-tag" style="padding-top:14px">Definitions from your installed<br>Microchip ${esc(S.device.pack)}.</div>`;$('#showRegisters').onclick=()=>deviceView();$('#showPins').onclick=()=>pinsView();
 }else if(S.view==='config'){body.innerHTML=`<div class="tree-heading">CONFIGURATION BITS</div><div class="source-tag">Select values from the device pack, then apply CONFIG directives to the current assembly source.</div><button class="file-row" id="showConfigs">${icon('sliders')} Edit configuration</button>`;$('#showConfigs').onclick=configView;
 }else{body.innerHTML=`<div class="tree-heading">COURSE LIBRARY</div><div class="source-tag">Your labs and chip documentation, one click away.</div>`;}}
function renderTabs(){const tabs=$('#tabs');tabs.innerHTML=S.files.size?[...S.files].map(([p,f])=>`<button class="tab ${p===S.active&&!S.details?'active':''}" data-tab="${esc(p)}">${fileIcon(p)}<span class="name">${esc(p.split('/').pop())}</span>${f.dirty?'<span class="dirty"></span>':''}<span class="close-tab" data-close="${esc(p)}">×</span></button>`).join(''):'<span class="tab-placeholder">Workspace</span>';tabs.querySelectorAll('[data-tab]').forEach(b=>b.onclick=e=>{if(!e.target.closest('[data-close]'))showFile(b.dataset.tab);});tabs.querySelectorAll('[data-close]').forEach(b=>b.onclick=e=>{e.stopPropagation();closeFile(b.dataset.close);});}
async function safeOpen(path,line){try{await openFile(path,line);}catch(e){toast(e.message,true);}}
async function openFile(path,line){if(!S.files.has(path)){const file=await api('read',{path});S.files.set(path,{...file,dirty:false});}showFile(path);if(line)E.go(line);}
function showFile(path){S.active=path;S.details=null;const f=S.files.get(path);$('#welcome').hidden=true;$('#detail').hidden=true;$('#editor').hidden=false;E.open(path,f.content,f.readOnly||S.debug!=='disconnected');$('#breadcrumbs').innerHTML=`<span>${esc(S.project.name)}</span><span>›</span><span>Source</span><span>›</span><span>${esc(path.split('/').pop())}</span>`;$('#encodingStatus').textContent=f.encoding==='latin1'?'Latin-1':'UTF-8';$('#languageStatus').textContent=/\.(c|h|cpp)$/.test(path)?'C / C++':'PIC18 Assembly';renderTabs();renderSidebar();updateMarks();controls();}
async function closeFile(path){const f=S.files.get(path);if(f.dirty&&!await api('confirm',{title:'Discard unsaved changes?',message:path.split('/').pop()+' has unsaved edits.',accept:'Discard Changes'}))return;S.files.delete(path);E.close(path);if(S.active===path){S.active=null;const next=[...S.files.keys()].pop();if(next)showFile(next);else welcome();}renderTabs();renderSidebar();controls();}
async function saveFile(path=S.active){if(!path)return;const f=S.files.get(path);if(!f.dirty)return;const r=await api('save',{path,content:f.content,digest:f.digest,encoding:f.encoding});f.digest=r.digest;f.dirty=false;renderTabs();renderSidebar();}
async function saveAll(){for(const [p,f] of S.files)if(f.dirty)await saveFile(p);}
async function canSwitch(){if(S.busy)return false;if(S.debug!=='disconnected'){toast('Stop the debug session before switching projects.');return false;}if([...S.files.values()].some(f=>f.dirty)){return await api('confirm',{title:'Open another project?',message:'Unsaved edits will be discarded. Cancel to save your work first.',accept:'Discard and Open'});}return true;}
async function openProject(path){if(!await canSwitch())return;await task('Opening project…',async()=>{if(!path)path=await api('chooseProject');if(!path)return;const p=await api('open',{path});await loaded(p);});}
async function loaded(p){S.project=p;S.files.clear();S.active=null;E.reset();S.view='files';S.diagnostics=[];S.output='';S.debugOutput='';S.memoryOutput='';S.breakpoints=[];S.stopwatch=null;S.location={};S.values={};S.debug='disconnected';$('#stopwatchClock').value=String(p.clockMHz??4);$('#problemCount').textContent='0';$('#projectTitle').innerHTML=esc(p.name)+' <span>⌄</span>';$('#configuration').innerHTML=p.configurations.map(c=>`<option ${c.name===p.configuration?'selected':''}>${esc(c.name)}</option>`).join('')||'<option>prebuilt</option>';$('#statusProject').textContent=p.name;$('#buildStatus').textContent='Project ready';$('#buildStatus').className='good';view('files');renderInspector();renderPanel();const first=sourceFiles()[0];if(first)await openFile(first.path);else welcome();}
async function newProject(){if(!await canSwitch())return;showModal(`<h2>Start a PIC18 project.</h2><p>Both templates open in MPLAB X 6.20 and include the course’s reset and interrupt vector placements.</p><button class="ref-card" id="newBasic">${icon('files')}<div><strong>Assembly starter</strong><small>A simple counter for learning the editor and debugger.</small></div>${icon('arrow')}</button><button class="ref-card" id="newInterrupt">${icon('chip')}<div><strong>Interrupt bench</strong><small>INT0 on RB0, an ISR, and a counter you can watch.</small></div>${icon('arrow')}</button><div class="modal-actions"><button class="button" data-dismiss>Cancel</button></div>`);const create=template=>{ $('#modal').close();task('Creating project…',async()=>{const path=await api('chooseNew');if(!path)return;await loaded(await api('new',{path,template}));if(template==='interrupt')addWatch('irq_count');toast('Project created. Build it or start the simulator.');});};$('#newBasic').onclick=()=>create('basic');$('#newInterrupt').onclick=()=>create('interrupt');}

function welcome(){S.details=null;$('#editor').hidden=true;$('#detail').hidden=true;$('#welcome').hidden=false;$('#breadcrumbs').innerHTML='<span>Aster</span><span>›</span><span>Getting started</span>';$('#welcome').innerHTML=`<div class="welcome-inner"><div class="eyebrow"><span class="tiny-dot"></span> YOUR BENCH, REIMAGINED</div><h1>A little closer<br>to the <span>hardware.</span></h1><p class="intro">Write, build, and explore your PIC firmware.<br>A focused workspace for your avionics labs.</p><div class="welcome-actions"><button class="button primary" id="welcomeOpen">${icon('folder')} Open project</button><button class="button" id="welcomeNew">＋ New project</button></div><div class="section-label">PICK UP WHERE YOU LEFT OFF <span>${S.recent.length} PROJECTS</span></div>${S.recent.slice(0,3).map((p,i)=>`<button class="recent-card" data-recent="${i}">${icon('folder')}<div><strong>${esc(p.split('/').pop())}</strong><small>${esc(p.replace(/^\/Users\/[^/]+/,'~'))}</small></div><span class="arrow">↗</span></button>`).join('')}<div class="welcome-meta"><span>${icon('check')} MPLAB project compatible</span><span>${icon('chip')} PIC18F87K22</span><span>${icon('shield')} Runs locally</span></div></div>`;$('#welcomeOpen').onclick=()=>openProject();$('#welcomeNew').onclick=newProject;$('#welcome').querySelectorAll('[data-recent]').forEach(b=>b.onclick=()=>openProject(S.recent[+b.dataset.recent]));renderTabs();}
function view(name){S.view=name;$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));renderSidebar();if(name==='device')deviceView();if(name==='config')configView();if(name==='reference')referenceView();if(name==='files'||name==='search'){if(S.active)showFile(S.active);else welcome();}}
function detail(title,html){S.details=title;$('#editor').hidden=true;$('#welcome').hidden=true;$('#detail').hidden=false;$('#detail').innerHTML=`<div class="detail-inner">${html}</div>`;$('#breadcrumbs').innerHTML=`<span>PIC18F87K22</span><span>›</span><span>${esc(title)}</span>`;renderTabs();}
function deviceView(){detail('Device & registers',`<div class="eyebrow">DEVICE REFERENCE</div><h2>PIC18F87K22</h2><p>The registers, fields, and addresses of your chip. Add any register to Watches to inspect it during a debug session.</p><div class="chip-stat-grid"><div class="chip-stat"><strong>128 KB</strong><small>Program flash</small></div><div class="chip-stat"><strong>3,896 B</strong><small>Data RAM</small></div><div class="chip-stat"><strong>1 KB</strong><small>EEPROM</small></div></div><div class="filter-row"><input id="registerFilter" class="input" placeholder="Find a register or bit field…" aria-label="Find a register"></div><table class="detail-table"><thead><tr><th>REGISTER</th><th>ADDRESS</th><th>BIT FIELDS</th><th></th></tr></thead><tbody id="registerTable"></tbody></table>`);function table(q=''){$('#registerTable').innerHTML=S.device.registers.filter(r=>(r.name+' '+r.bits.join(' ')).toLowerCase().includes(q.toLowerCase())).map(r=>`<tr><td>${esc(r.name)}</td><td style="font-family:var(--mono)">${esc(r.address)}</td><td>${esc(r.bits.join(' · '))}</td><td><button class="text-button" data-watch="${esc(r.name)}">+ Watch</button></td></tr>`).join('');$$('[data-watch]').forEach(b=>b.onclick=()=>addWatch(b.dataset.watch));}table();$('#registerFilter').oninput=e=>table(e.target.value);}
function pinsView(){detail('80-pin package',`<div class="eyebrow">PACKAGE REFERENCE</div><h2>Every pin, in one place.</h2><p>Device-pack pin order and multiplexed signals. Check the EasyPIC board schematic for header routing and jumper positions.</p><button id="openBoardManual" class="button">${icon('book')} Open board manual</button><div class="pins-grid">${S.device.pins.map((p,i)=>`<div class="pin-item"><b>${i+1}</b><span>${esc(p.signals.map(s=>s.cname||s.name||Object.values(s).join(' ')).join(' / '))}</span></div>`).join('')}</div>`);$('#openBoardManual').onclick=()=>api('openDoc',{key:'board'}).catch(e=>toast(e.message,true));}
function configView(){const file=S.active?S.files.get(S.active):null;const selected={},removed=new Set();for(const m of (file?.content||'').matchAll(/^\s*CONFIG\s+(\w+)\s*=\s*(\w+)/gim)){const key=m[1].toUpperCase(),def=S.device.configs.find(c=>c.name===key||(c.aliases||[]).includes(key));selected[def?.name||key]=m[2].toUpperCase();}detail('Configuration bits',`<div class="eyebrow">DEVICE CONFIGURATION</div><h2>Make the settings explicit.</h2><p>These options come directly from your PIC18F87K22 device pack. Only selected fields are emitted. Applying updates matching CONFIG lines and adds new ones to the active assembly file.</p><div class="inline-notice">Editing ${file?esc(S.active.split('/').pop()):'no source file'}. Configuration changes take effect after building and programming. Review clock and watchdog settings against your lab.</div><div class="filter-row"><input id="configFilter" class="input" placeholder="Filter configuration fields…" aria-label="Filter configuration fields"><button class="button primary" id="applyConfig">Apply to source</button></div><textarea id="configCode" class="input config-output" readonly aria-label="Generated configuration source"></textarea><table class="detail-table"><thead><tr><th>FIELD</th><th>SETTING</th><th>DESCRIPTION</th></tr></thead><tbody id="configTable"></tbody></table>`);
 function output(){$('#configCode').value=Object.entries(selected).map(([k,v])=>`CONFIG ${k} = ${v}`).join('\n');}
 function table(q=''){$('#configTable').innerHTML=S.device.configs.filter(c=>(c.name+' '+c.description).toLowerCase().includes(q.toLowerCase())).map((c)=>`<tr><td title="${esc(c.register)}">${esc(c.name)}</td><td><select data-config="${esc(c.name)}" aria-label="${esc(c.name)}"><option value="">Unspecified</option>${c.options.map(o=>`<option value="${esc(o.name)}" ${selected[c.name]===o.name?'selected':''}>${esc(o.name)}</option>`).join('')}</select></td><td>${esc(c.description)}</td></tr>`).join('');$$('[data-config]').forEach(el=>el.onchange=()=>{if(el.value){selected[el.dataset.config]=el.value;removed.delete(el.dataset.config);}else{delete selected[el.dataset.config];removed.add(el.dataset.config);}output();});}table();output();$('#configFilter').oninput=e=>table(e.target.value);$('#applyConfig').disabled=!file||file.readOnly||S.debug!=='disconnected'||!(/\.(asm|s)$/i.test(S.active||''));$('#applyConfig').onclick=()=>{let content=file.content;const variants=name=>[name,...(S.device.configs.find(c=>c.name===name)?.aliases||[])].join('|');for(const name of removed)content=content.replace(new RegExp(`^\\s*CONFIG\\s+(?:${variants(name)})\\s*=[^\\r\\n]*(?:\\r?\\n|$)`,'im'),'');const added=[];for(const [name,value]of Object.entries(selected)){const re=new RegExp(`^(\\s*CONFIG\\s+(?:${variants(name)})\\s*=\\s*)\\w+`,'im');if(re.test(content))content=content.replace(re,`$1${value}`);else added.push(`CONFIG ${name} = ${value}`);}if(added.length){const include=/^#include[^\r\n]*\r?\n/m;if(include.test(content))content=content.replace(include,m=>m+'\n'+added.join('\n')+'\n');else content=added.join('\n')+'\n\n'+content;}showFile(S.active);E.replace(content);toast('Configuration updated in the editor. Save and build to apply.');};}
function referenceView(){const docs=[['lab1','Lab 1 · Development board','Board setup, programming, and serial communication'],['lab2','Lab 2 · Development environment','Simulation, breakpoints, registers, and memory'],['lab3','Lab 3 · Basic input and output','Digital I/O and your lab workflow'],['datasheet','PIC18F87K22 datasheet','The complete chip reference'],['board','EasyPIC PRO v7 manual','Pins, headers, jumpers, and peripherals'],['assembler','PIC assembler guide · XC8 2.46','Directives, linker options, and output files']];detail('Course references',`<div class="eyebrow">AT YOUR WORKBENCH</div><h2>The right reference, nearby.</h2><p>Your course documents open in your Mac’s PDF reader.</p>${docs.map(([k,n,d])=>`<button class="ref-card" data-doc="${k}">${icon('book')}<div><strong>${n}</strong><small>${d}</small></div>${icon('arrow')}</button>`).join('')}`);$$('[data-doc]').forEach(b=>b.onclick=()=>api('openDoc',{key:b.dataset.doc}).catch(e=>toast(e.message,true)));}
async function projectSearch(query){if(!query||!S.project)return;const results=[];for(const f of sourceFiles()){let content=S.files.get(f.path)?.content;if(content===undefined){try{content=(await api('read',{path:f.path})).content;}catch{continue;}}content.split('\n').forEach((text,i)=>{if(text.toLowerCase().includes(query.toLowerCase())&&results.length<150)results.push({path:f.path,name:f.name,line:i+1,text});});}const target=$('#searchResults');if(!target||$('#projectSearch')?.value!==query)return;target.className='';target.innerHTML=results.length?results.map((r,i)=>`<button class="search-result" data-result="${i}"><strong>${esc(r.name)} : ${r.line}</strong><small>${esc(r.text.trim())}</small></button>`).join(''):'<div class="source-tag" style="padding-top:16px">No matches.</div>';target.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>{const r=results[+b.dataset.result];safeOpen(r.path,r.line);});}
function renderPanel(){const body=$('#panelBody');
 if(S.panel==='output'){body.innerHTML=S.output?`<pre class="console">${esc(S.output)}</pre>`:`<div class="panel-empty"><strong>Your next build starts here.</strong><p>Build a project to see compiler output and navigate errors.</p><div><span class="tiny-dot"></span> XC8 2.46 &nbsp; / &nbsp; MPLAB X 6.20</div></div>`;body.scrollTop=body.scrollHeight;
 }else if(S.panel==='problems'){body.innerHTML=S.diagnostics.length?S.diagnostics.map((d,i)=>`<button class="problem-row" data-problem="${i}"><span class="problem-badge">${d.severity==='warning'?'△':'⊗'}</span><div>${esc(d.message)}<small>${esc(d.path.split('/').pop())} [${d.line}, ${d.column}] · ${esc(d.severity)}</small></div></button>`).join(''):'<div class="panel-empty"><strong>No compiler diagnostics.</strong><p>Build your project to check for errors and warnings.</p></div>';$$('[data-problem]').forEach(b=>b.onclick=()=>{const d=S.diagnostics[+b.dataset.problem];safeOpen(d.path,d.line);});
 }else if(S.panel==='debug'){const focus=document.activeElement?.id==='debugCommand',value=$('#debugCommand')?.value||'';body.innerHTML=`<div class="debug-layout"><div class="debug-output"><pre class="console">${esc(S.debugOutput||'Start a debug session to connect to Microchip MDB.\n')}</pre></div><form class="console-input-row" id="debugForm"><input class="input" id="debugCommand" aria-label="MDB command" placeholder="MDB command · help, print /x WREG, backtrace" value="${esc(value)}"><button class="button" ${S.debug==='disconnected'?'disabled':''}>Send</button></form></div>`;$('.debug-output').scrollTop=$('.debug-output').scrollHeight;if(focus)$('#debugCommand').focus();$('#debugForm').onsubmit=e=>{e.preventDefault();const command=$('#debugCommand').value.trim();if(!command)return;$('#debugCommand').value='';task('Debugger command…',async()=>{S.debugOutput+='\n› '+command+'\n';const result=await api('debugCommand',{command});if(S.panel==='debug')renderPanel();if(S.debug==='paused')await refreshRegisters();});};
 }else if(S.panel==='memory'){body.innerHTML=`<div class="panel-control-row"><select id="memoryType" aria-label="Memory type"><option value="r">File registers</option><option value="p">Program memory</option><option value="c">Configuration</option><option value="e">EEPROM</option></select><input id="memoryAddress" class="input small" aria-label="Memory address" value="${esc(S.memoryAddress||'0x0000')}"><select id="memoryFormat" aria-label="Memory display"><option value="xb">Hex bytes</option><option value="i">Disassembly</option></select><button id="readMemory" class="button">Read 64</button></div><pre class="console">${esc(S.memoryOutput||'Pause the target, then read memory at an address.\n')}</pre>`;$('#memoryType').value=S.memoryType||'r';$('#memoryFormat').value=S.memoryFormat||'xb';$('#readMemory').onclick=()=>task('Reading memory…',async()=>{S.memoryType=$('#memoryType').value;S.memoryAddress=$('#memoryAddress').value;S.memoryFormat=$('#memoryFormat').value;const raw=await api('memory',{type:S.memoryType,address:S.memoryAddress,format:S.memoryFormat,count:64});S.memoryOutput=formatMemory(raw,S.memoryAddress,S.memoryFormat);renderPanel();});
 }else if(S.panel==='interrupts'){
 const ready=S.debug==='paused'&&$('#debugTarget').value==='SIM';
 body.innerHTML=`<div class="interrupt-panel"><div class="interrupt-column"><div class="section-label">SIMULATOR INPUT PINS</div><div class="interrupt-actions"><select id="stimulusPin" aria-label="Simulator input pin">${['RB0','RB1','RB2','RB3','RA0','RA1','RD0','RD1','RD2'].map(pin=>`<option ${pin===(S.stimulusPin||'RB0')?'selected':''}>${pin}</option>`).join('')}</select><button class="button" id="pinLow" ${ready?'':'disabled'}>Set low</button><button class="button" id="pinHigh" ${ready?'':'disabled'}>Set high</button></div><p>RB0 is INT0. Set the pin low, step to sample it, then set it high to test a rising edge.</p></div><div class="interrupt-column"><div class="section-label">RAISE AN INTERRUPT FLAG</div><div class="interrupt-actions"><select id="interruptSource" aria-label="Interrupt source">${['INT0','INT1','INT2','TMR0','TMR1','TMR2','ADC'].map(n=>`<option>${n}</option>`).join('')}</select><button class="button" id="triggerInterrupt" ${ready?'':'disabled'}>Raise flag</button><button class="text-button" id="watchInterrupts">Watch flags</button></div><p>Pause the simulator first. Enable interrupts in your firmware, raise a flag, then step or continue into the ISR.</p></div></div><pre class="console" id="stimulusResult">${esc(S.stimulusResult||'Simulator controls only. Hardware interrupts come from your board.')}</pre>`;
 const setPin=high=>task('Changing simulator input…',async()=>{S.stimulusPin=$('#stimulusPin').value;S.stimulusResult=await api('setPin',{pin:S.stimulusPin,high});await refreshRegisters();renderPanel();});$('#pinLow').onclick=()=>setPin(false);$('#pinHigh').onclick=()=>setPin(true);
 $('#triggerInterrupt').onclick=()=>task('Raising interrupt flag…',async()=>{S.stimulusResult=await api('triggerInterrupt',{source:$('#interruptSource').value});await refreshRegisters();renderPanel();});$('#watchInterrupts').onclick=()=>{for(const n of ['INTCON','INTCON2','INTCON3','PIR1','PIE1','RCON'])if(!S.watches.includes(n))S.watches.push(n);renderInspector();if(S.debug==='paused')task('Reading interrupt flags…',refreshRegisters);};
 }else if(S.panel==='serial'){const focus=document.activeElement?.id==='serialInput',value=$('#serialInput')?.value||'';body.innerHTML=`<div class="serial-layout"><div class="panel-control-row"><select id="serialPort" aria-label="Serial port">${S.ports.length?S.ports.map(p=>`<option value="${esc(p)}">${esc(p.replace('/dev/',''))}</option>`).join(''):'<option value="">No ports found</option>'}</select><select id="serialBaud" aria-label="Baud rate">${[9600,19200,38400,57600,115200].map(b=>`<option ${b===S.baud?'selected':''}>${b}</option>`).join('')}</select><span>8-N-1</span><button class="button" id="serialConnect">${S.serial?'Disconnect':'Connect'}</button><button class="mini-icon" id="refreshPorts" title="Refresh ports" aria-label="Refresh ports">↻</button></div><div class="serial-output"><pre class="console">${esc(S.serialOutput||'Serial terminal ready. Course default: 19200 baud, 8-N-1, LF.\n')}</pre></div><form id="serialForm" class="console-input-row"><input id="serialInput" class="input" value="${esc(value)}" placeholder="Send a line…" aria-label="Serial message"><select id="serialEnding" aria-label="Line ending"><option value="lf">LF</option><option value="crlf">CRLF</option><option value="none">None</option></select><button class="button" ${S.serial?'':'disabled'}>Send</button></form></div>`;if(S.port)$('#serialPort').value=S.port;$('#serialPort').disabled=S.serial;$('#serialBaud').disabled=S.serial;$('.serial-output').scrollTop=$('.serial-output').scrollHeight;if(focus)$('#serialInput').focus();$('#refreshPorts').onclick=async()=>{S.ports=await api('serialPorts');renderPanel();};$('#serialConnect').onclick=()=>task(S.serial?'Disconnecting…':'Connecting serial…',async()=>{if(S.serial)await api('serialDisconnect');else{S.port=$('#serialPort').value;S.baud=+$('#serialBaud').value;await api('serialConnect',{path:S.port,baud:S.baud});}S.serial=!S.serial;renderPanel();});$('#serialForm').onsubmit=async e=>{e.preventDefault();const ending=$('#serialEnding').value,text=$('#serialInput').value+(ending==='lf'?'\n':ending==='crlf'?'\r\n':'');try{await api('serialSend',{text});$('#serialInput').value='';}catch(e){toast(e.message,true);}};
 }}
function formatMemory(raw,address,format){if(format==='i')return raw;const bytes=raw.trim().split(/\s+/);if(!bytes.every(b=>/^[0-9a-f]{2}$/i.test(b)))return address+'\n'+raw;const start=address.toLowerCase().startsWith('0x')?parseInt(address,16):parseInt(address,10);let lines=['ADDRESS    00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F',''];for(let i=0;i<bytes.length;i+=16)lines.push('0x'+(start+i).toString(16).toUpperCase().padStart(6,'0')+'   '+bytes.slice(i,i+16).join(' ').toUpperCase());return lines.join('\n');}
function formatHex(value){if(value===undefined)return '—';if(/^(0x)?[0-9a-f]+$/i.test(value)){const clean=value.replace(/^0x/i,'');return '0x'+clean.toUpperCase().padStart(2,'0');}return value==='Symbol does not exist.'?'unavailable':value;}
function registerRows(names){return names.map(name=>`<div class="register-row"><span>${esc(name)}</span><button class="reg-value ${S.previous[name]!==undefined&&S.previous[name]!==S.values[name]?'changed':''}" data-edit="${esc(name)}" title="Edit ${esc(name)}" ${S.debug!=='paused'?'disabled':''}>${esc(formatHex(S.values[name]))}</button>${S.watches.includes(name)?`<button class="mini-icon" data-remove-watch="${esc(name)}" title="Remove watch">×</button>`:''}</div>`).join('');}
function renderInspector(){$('#coreRegisters').innerHTML=registerRows(['WREG','STATUS','BSR']);$('#watchRegisters').innerHTML=registerRows(S.watches);const status=S.values.STATUS===undefined?null:parseInt(S.values.STATUS.replace(/^0x/i,''),16);$('#statusBits').innerHTML=['N','OV','Z','DC','C'].map((name,i)=>`<div class="bit ${status!==null&&(status>>(4-i)&1)?'on':''}">${name}<span>${status===null?'—':(status>>(4-i)&1)}</span></div>`).join('');$('#pcValue').textContent=S.location.address?S.location.address.toUpperCase().replace('0X','0x'):'—';$('#pcLocation').textContent=S.location.file?S.location.file.split('/').pop()+' : '+S.location.line:(S.debug==='disconnected'?'Start a session to inspect execution':'At reset vector');$('#breakpointCount').textContent=S.breakpoints.length;$('#breakpoints').className=S.breakpoints.length?'':'empty-small';$('#breakpoints').innerHTML=S.breakpoints.length?S.breakpoints.map((b,i)=>`<div class="bp-row"><span class="bp-dot">●</span><button data-bp-go="${i}">${esc(b.path.split('/').pop())}:${b.line}</button><button class="mini-icon" data-bp-delete="${i}" title="Remove breakpoint">×</button></div>`).join(''):'Click a line number or its left margin to set a breakpoint. Then press Continue (F5).';$$('[data-edit]').forEach(b=>b.onclick=()=>editRegister(b.dataset.edit));$$('[data-remove-watch]').forEach(b=>b.onclick=()=>{S.watches=S.watches.filter(n=>n!==b.dataset.removeWatch);renderInspector();});$$('[data-bp-go]').forEach(b=>b.onclick=()=>{const p=S.breakpoints[+b.dataset.bpGo];safeOpen(p.path,p.line);});$$('[data-bp-delete]').forEach(b=>b.onclick=()=>{const p=S.breakpoints[+b.dataset.bpDelete];toggleBreakpoint(p.path,p.line);});controls();}
function names(){return [...new Set(['WREG','STATUS','BSR',...S.watches])];}
async function refreshRegisters(){if(S.debug!=='paused')return;applyInspection(await api('inspect',{names:names()}));}
function applyInspection(data){if(data.state)S.debug=data.state;if(data.location)S.location=data.location;if(data.breakpoints)S.breakpoints=data.breakpoints;if(data.stopwatch)S.stopwatch=data.stopwatch;S.previous={...S.values};for(const r of data.registers||[])S.values[r.name]=r.value;renderInspector();updateMarks();}
function updateMarks(){if(!S.active)return;const loc=S.location;E.marks(S.breakpoints.filter(b=>b.path===S.active).map(b=>b.line),loc.file===S.active&&S.debug!=='disconnected'?loc.line:0,S.diagnostics.filter(d=>d.path===S.active&&d.severity!=='note').map(d=>d.line));}
async function build(){await task('Building…',async()=>{await saveAll();panel('output');await api('build');});}
async function clean(){await task('Cleaning…',async()=>{panel('output');await api('clean');});}
async function startDebug(){await task('Starting debugger…',async()=>{stopwatchClock();await saveAll();panel('output');const tool=$('#debugTarget').value;S.debugOutput='';applyInspection(await api('debugStart',{tool,index:S.toolIndex||0,clockMHz:stopwatchClock(),accumulateStopwatch:$('#stopwatchAccumulate').checked}));await refreshRegisters();toast(tool==='SIM'?'Simulator ready. Press Continue (F5) to run to a breakpoint, or Step (F11).':'PICkit 3 session ready.');});}
async function debugAction(action){await task(action==='stepi'?'Stepping…':action==='next'?'Stepping over…':action==='continue'?'Running…':action==='halt'?'Pausing…':action==='stop'?'Stopping debugger…':'Resetting…',async()=>{const r=await api('debugAction',{action,names:names()});applyInspection(r);if(action==='stop'){S.values={};S.location={};S.stopwatch=null;$('#callStack').textContent='No active session';renderInspector();updateMarks();$('#buildStatus').textContent='Debug session ended';$('#buildStatus').className='';}else if(S.location.file&&S.files.has(S.location.file)){showFile(S.location.file);E.go(S.location.line||1);} });}
async function toggleBreakpoint(path,line){await task('Updating breakpoint…',async()=>{const r=await api('breakpoint',{path,line});S.breakpoints=r.breakpoints;renderInspector();updateMarks();});}
function addWatch(name){if(!name){showModal(`<h2>Add a watch</h2><p>Enter an SFR or an assembly symbol from your program.</p><input id="watchName" class="input" list="registerSuggestions" placeholder="e.g. LATD or count"><datalist id="registerSuggestions">${S.device.registers.map(r=>`<option>${esc(r.name)}</option>`).join('')}</datalist><div class="modal-actions"><button class="button" data-dismiss>Cancel</button><button id="watchAdd" class="button primary">Add watch</button></div>`);$('#watchAdd').onclick=()=>{const n=$('#watchName').value.trim();if(!/^[A-Za-z_][A-Za-z0-9_.$]*$/.test(n)){toast('Enter a register or symbol name.',true);return;}$('#modal').close();addWatch(n);};$('#watchName').focus();return;}if(!S.watches.includes(name)&&!['WREG','STATUS','BSR'].includes(name))S.watches.push(name);renderInspector();if(S.debug==='paused')task('Reading watch…',refreshRegisters);else toast(name+' added to Watches.');}
function editRegister(name){showModal(`<h2>Edit ${esc(name)}</h2><p>Write one byte to the paused target’s data memory.</p><label class="form-label">VALUE (0–255 OR HEX)</label><input id="registerValue" class="input" value="${esc(formatHex(S.values[name]))}"><div class="modal-actions"><button class="button" data-dismiss>Cancel</button><button class="button primary" id="writeValue">Write value</button></div>`);$('#writeValue').onclick=()=>task('Writing register…',async()=>{await api('writeRegister',{name,value:$('#registerValue').value.trim()});$('#modal').close();await refreshRegisters();});$('#registerValue').focus();$('#registerValue').select();}
function showModal(html){$('#modalBody').innerHTML='<div class="modal-content">'+html+'</div>';$$('[data-dismiss]').forEach(b=>b.onclick=()=>$('#modal').close());$('#modal').showModal();}
async function settings(){showModal(`<h2>Your development tools.</h2><p>Aster uses the same compiler, debugger, and device pack as your MPLAB 6.20 projects.</p>${S.tools.map(t=>`<div class="tool-row"><span>${esc(t.name)} · ${esc(t.version)}</span><strong>${t.available?'✓ FOUND':'MISSING'}</strong></div>`).join('')}<label class="form-label">MPLAB X DIRECTORY</label><input id="mplabPath" class="input" value="${esc(S.tools[0]?.path.split('/mplab_platform')[0]||'/Applications/microchip/mplabx/v6.20')}"><label class="form-label">XC8 DIRECTORY</label><input id="xc8Path" class="input" value="${esc(S.tools[1]?.path.split('/pic-as')[0]||'/Applications/microchip/xc8/v2.46')}"><div class="modal-actions"><button class="button" data-dismiss>Close</button><button id="saveSettings" class="button primary">Save settings</button></div>`);$('#saveSettings').onclick=()=>task('Checking tools…',async()=>{S.tools=await api('settings',{mplab:$('#mplabPath').value,xc8:$('#xc8Path').value});$('#modal').close();toast('Tool paths updated.');});}
async function program(){if(!S.project)return;showModal(`<h2>Program your PIC18F87K22.</h2><p>Build the current source and program its production image using PICkit 3. Power the EasyPIC board from its own supply.</p><div class="tool-row"><span>Project</span><strong>${esc(S.project.name)}</strong></div><div class="tool-row"><span>Target power from PICkit</span><strong>OFF</strong></div><label class="form-label">TOOL INDEX</label><input id="programIndex" class="input" type="number" min="0" value="${S.toolIndex||0}"><button class="text-button" id="detectForProgram" style="margin-top:12px">Detect connected tools</button><pre class="console" id="detectedTools" style="max-height:150px;overflow:auto;padding:12px 0"></pre><div class="modal-actions"><button class="button" data-dismiss>Cancel</button><button id="confirmProgram" class="button primary">${icon('upload')} Build & program</button></div>`);$('#detectForProgram').onclick=()=>task('Detecting tools…',async()=>{$('#detectedTools').textContent=await api('detectTools');});$('#confirmProgram').onclick=()=>{S.toolIndex=+$('#programIndex').value;$('#modal').close();task('Programming device…',async()=>{await saveAll();panel('debug');const r=await api('program',{index:S.toolIndex});toast('Programming succeeded: '+r.image.split('/').pop());$('#buildStatus').textContent='Programming succeeded';$('#buildStatus').className='good';});};}
async function refreshStack(){await task('Reading call stack…',async()=>{$('#callStack').textContent=await api('stack');});}
const actions={open:()=>openProject(),new:newProject,save:()=>task('Saving…',()=>saveFile()),saveAll:()=>task('Saving…',saveAll),build,clean,debug:startDebug,stop:()=>debugAction('stop'),stepi:()=>debugAction('stepi'),next:()=>debugAction('next'),reset:()=>debugAction('reset'),toggleRun:()=>S.debug==='disconnected'?startDebug():debugAction(S.debug==='running'?'halt':'continue'),find:()=>E.find(),settings,regenerate:()=>task('Regenerating makefiles…',async()=>{await saveAll();panel('output');await api('regenerate');toast('Makefiles regenerated.');}),reveal:()=>api('reveal'),program};
function commandPalette(){const commands=[['Open project','open','⌘O'],['Create assembly project','new','⌘N'],['Build project','build','⌘B'],['Save all files','saveAll','⇧⌘S'],['Start debugging','debug','⌘D'],['Program PICkit 3','program',''],['Clean project','clean',''],['Regenerate makefiles','regenerate',''],['Toolchain settings','settings','⌘,'],['Reveal project in Finder','reveal','']];showModal(`<input id="commandInput" class="input" placeholder="Search commands or open files…" aria-label="Search commands"><div class="modal-list" id="commandResults" style="margin-top:12px"></div>`);function results(q=''){const list=[...commands.map(([label,action,key])=>({label,action,key})),...(S.project?.files||[]).map(f=>({label:f.name,path:f.path,key:''}))].filter(c=>c.label.toLowerCase().includes(q.toLowerCase()));$('#commandResults').innerHTML=list.map((c,i)=>`<button class="command-item" data-command="${i}">${icon(c.path?'files':'arrow')}${esc(c.label)}<kbd>${c.key}</kbd></button>`).join('');$$('[data-command]').forEach(b=>b.onclick=()=>{const c=list[+b.dataset.command];$('#modal').close();c.path?safeOpen(c.path):actions[c.action]?.();});}results();$('#commandInput').oninput=e=>results(e.target.value);$('#commandInput').focus();}
window.asterEvent=(name,data)=>{
 if(name==='menu'){actions[data]?.();return;}
 if(name==='buildStart'){S.output='';S.diagnostics=[];$('#problemCount').textContent='0';$('#cancelBuild').hidden=false;panel('output');}
 if(name==='buildOutput')log(data);
 if(name==='buildEnd'){S.diagnostics=data.diagnostics;$('#problemCount').textContent=S.diagnostics.length;if(S.project)S.project.outputs=data.outputs;renderSidebar();updateMarks();const label=data.ok?(data.clean?'Clean complete':`Build succeeded · ${data.elapsed.toFixed(2)}s`):'Build failed';$('#buildStatus').textContent=label;$('#buildStatus').className=data.ok?'good':'bad';log('\n'+label+'\n');if(!data.ok&&S.diagnostics.length)panel('problems');}
 if(name==='debugOutput'){S.debugOutput=(S.debugOutput+data).slice(-300000);if(S.panel==='debug')renderPanel();}
 if(name==='debugState'){S.debug=data.state;renderInspector();controls();if(S.panel==='interrupts')renderPanel();}
 if(name==='debugStopped'){S.debug='paused';S.location=data;renderInspector();updateMarks();$('#buildStatus').textContent='Paused · '+data.address;$('#buildStatus').className='good';if(!S.busy){refreshRegisters().catch(e=>toast(e.message,true));if(S.files.has(data.file)){showFile(data.file);E.go(data.line);}}}
 if(name==='serialData'){S.serialOutput=(S.serialOutput+data).slice(-200000);if(data.includes('[Serial device disconnected]'))S.serial=false;if(S.panel==='serial')renderPanel();}
 if(name==='requestClose'){(async()=>{if([...S.files.values()].some(f=>f.dirty)){if(!await api('confirm',{title:'Quit with unsaved changes?',message:'Unsaved changes will be discarded. Cancel to save your files first.',accept:'Discard and Quit'}))return;}if(S.busy&&!await api('confirm',{title:'An operation is still running.',message:'Quit will stop active tools and disconnect the debugger.',accept:'Stop and Quit'}))return;await api('closeApproved');})();}
};
E.init($('#editor'),{save:()=>actions.save(),change:(path,content)=>{const f=S.files.get(path);if(f){f.content=content;f.dirty=true;renderTabs();renderSidebar();}},cursor:(line,col)=>$('#cursorStatus').textContent=`Ln ${line}, Col ${col}`,breakpoint:toggleBreakpoint});
$('#stopwatchClock').onchange=()=>{try{stopwatchClock();renderStopwatch();}catch(e){toast(e.message,true);}};
$('#stopwatchAccumulate').onchange=renderStopwatch;
$('#resetStopwatch').onclick=()=>task('Resetting stopwatch…',async()=>{S.stopwatch=await api('resetStopwatch');renderStopwatch();});
$('#openButton').onclick=()=>openProject();$('#projectTitle').onclick=()=>openProject();$('#newButton').onclick=newProject;$('#saveButton').onclick=()=>actions.save();$('#buildButton').onclick=build;$('#cleanButton').onclick=clean;$('#debugButton').onclick=startDebug;$('#programButton').onclick=program;$('#settingsButton').onclick=settings;$('#commandButton').onclick=commandPalette;$('#addWatch').onclick=()=>addWatch();$('#refreshRegisters').onclick=()=>task('Reading registers…',refreshRegisters);$('#refreshStack').onclick=refreshStack;$('#cancelBuild').onclick=()=>api('cancel');
$$('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));$$('[data-panel]').forEach(b=>b.onclick=()=>panel(b.dataset.panel));$$('[data-debug]').forEach(b=>b.onclick=()=>debugAction(b.dataset.debug));
$('#clearPanel').onclick=()=>{if(S.panel==='output')S.output='';else if(S.panel==='debug')S.debugOutput='';else if(S.panel==='serial')S.serialOutput='';else if(S.panel==='memory')S.memoryOutput='';renderPanel();};
$('#debugTarget').onchange=()=>{renderStopwatch();const hw=$('#debugTarget').value==='PICkit3';$('#targetNote').innerHTML=`<span class="tiny-dot"></span> ${hw?'External board power required':'No board needed'}`;$('#inspectorFoot').textContent=hw?'PICkit power supply stays off':'Simulator selected';if(hw){showModal('<h2>PICkit 3 debug target</h2><p>Use the index reported by Detect tools. The board must supply its own power.</p><input id="debugToolIndex" class="input" type="number" min="0" value="'+(S.toolIndex||0)+'"><button id="detectDebugTools" class="text-button" style="margin-top:12px">Detect tools</button><pre class="console" id="debugToolList"></pre><div class="modal-actions"><button class="button primary" id="setDebugIndex">Use target</button></div>');$('#detectDebugTools').onclick=()=>task('Detecting tools…',async()=>{$('#debugToolList').textContent=await api('detectTools');});$('#setDebugIndex').onclick=()=>{S.toolIndex=+$('#debugToolIndex').value;$('#modal').close();};}};
$('#configuration').onchange=()=>task('Selecting configuration…',async()=>{S.project=await api('configuration',{name:$('#configuration').value});$('#stopwatchClock').value=String(S.project.clockMHz??4);renderStopwatch();renderSidebar();});
$('#panelResizer').onpointerdown=e=>{const start=e.clientY,old=$('.bottom-panel').getBoundingClientRect().height;$('#panelResizer').setPointerCapture(e.pointerId);$('#panelResizer').onpointermove=ev=>document.documentElement.style.setProperty('--bottom',Math.max(120,Math.min(window.innerHeight*.55,old+start-ev.clientY))+'px');$('#panelResizer').onpointerup=()=>$('#panelResizer').onpointermove=null;};
document.addEventListener('keydown',e=>{if(e.metaKey&&e.key.toLowerCase()==='k'){e.preventDefault();commandPalette();}else if(e.metaKey&&e.key.toLowerCase()==='b'){e.preventDefault();if(!$('#buildButton').disabled)build();}else if(e.metaKey&&e.key.toLowerCase()==='o'){e.preventDefault();openProject();}else if(e.key==='F5'){e.preventDefault();e.shiftKey?debugAction('stop'):actions.toggleRun();}else if(e.key==='F10'){e.preventDefault();if(S.debug==='paused')debugAction('next');}else if(e.key==='F11'){e.preventDefault();if(S.debug==='paused')debugAction('stepi');}});
async function boot(){try{const b=await api('bootstrap');Object.assign(S,{recent:b.recent,device:b.device,tools:b.tools,ports:b.ports});E.setDevice(S.device.registers);$('#toolStatus').textContent=S.tools.every(t=>t.available)?'XC8 2.46 · MPLAB 6.20':'Toolchain needs setup';welcome();renderSidebar();renderInspector();renderPanel();controls();if(b.testMode)setTimeout(()=>uiTest(b.testProject),200);else if(b.initialProject)await loaded(await api('open',{path:b.initialProject}));}catch(e){toast(e.message,true);welcome();renderInspector();renderPanel();}}
async function uiTest(path){const checks=[];try{
 await loaded(await api('open',{path}));checks.push({name:'Open MPLAB project in native WebKit',ok:!!S.active});
 const original=E.content();E.replace('; UI integration save check\n'+original);await saveAll();const read=await api('read',{path:S.active});checks.push({name:'Edit and save through native bridge',ok:read.content.includes('UI integration save check')});
 view('config');const reten=$('[data-config="RETEN"]');reten.value='OFF';reten.dispatchEvent(new Event('change'));$('#applyConfig').click();await saveAll();checks.push({name:'Apply configuration without duplicating alias fields',ok:/CONFIG\s+RETEN\s*=\s*OFF/.test(E.content())&&((E.content().match(/CONFIG\s+EB(?:TR|RT)0\s*=/g)||[]).length===1)});
 await build();checks.push({name:'Production build',ok:$('#buildStatus').textContent.includes('succeeded')});
 checks.push({name:'Stopwatch inherits the selected project clock and defaults to per-run timing',ok:Number($('#stopwatchClock').value)===S.project.clockMHz&&!$('#stopwatchAccumulate').checked});$('#stopwatchClock').value='4';await startDebug();checks.push({name:'Stopwatch begins at zero with clock locked',ok:S.stopwatch?.cycles==='0'&&$('#stopwatchClock').disabled&&!$('#resetStopwatch').disabled});checks.push({name:'Start simulator',ok:S.debug==='paused'});
 for(let i=0;i<5;i++){const r=await api('debugAction',{action:'stepi',names:names()});applyInspection(r);}
 checks.push({name:'Stopwatch displays executed cycles after stepping',ok:Number(S.stopwatch?.cycles)>0&&$('#stopwatchCycles').textContent.includes('instruction cycles')});
 const beforeStopwatchReset=JSON.stringify(S.location);$('#resetStopwatch').click();while(S.busy)await new Promise(r=>setTimeout(r,20));checks.push({name:'Reset stopwatch button clears time without moving CPU',ok:S.stopwatch?.cycles==='0'&&$('#stopwatchTime').textContent==='0 ns'&&JSON.stringify(S.location)===beforeStopwatchReset});
 checks.push({name:'Live WREG after stepping',ok:!!S.values.WREG&&S.values.WREG!=='Symbol does not exist.'});
 view('device');checks.push({name:'Device reference',ok:$$('#registerTable tr').length>200});
 view('config');checks.push({name:'Configuration editor',ok:$$('[data-config]').length>50});
 await debugAction('stop');
 const newPath=path.replace(/\/[^/]+$/, '/CreatedInterruptUIProject.X');
 await loaded(await api('new',{path:newPath,template:'interrupt'}));checks.push({name:'Creates MPLAB-compatible interrupt project',ok:E.content().includes('highISR:')});
 S.watches=['irq_count','INTCON','INTCON2','INTCON3'];const source=E.content(),idleLine=source.split('\n').findIndex(l=>l.includes('nop     ; idle loop'))+1,isrLine=source.split('\n').findIndex(l=>l.includes('incf    irq_count'))+1;
 async function until(test){const deadline=Date.now()+5000;while(!test()){if(Date.now()>deadline)throw Error('Timed out waiting for breakpoint UI');await new Promise(r=>setTimeout(r,30));}}
 async function gutterClick(line,margin=false){E.go(line);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const number=$$('.cm-lineNumbers .cm-gutterElement').find(el=>el.textContent===String(line)&&el.style.visibility!=='hidden');if(!number)throw Error('Line number is not visible');const rect=number.getBoundingClientRect(),gutter=$('.cm-breakpoint-gutter').getBoundingClientRect(),x=margin?(gutter.left+gutter.right)/2:(rect.left+rect.right)/2,y=(rect.top+rect.bottom)/2;const target=document.elementFromPoint(x,y);if(!target?.closest(margin?'.cm-breakpoint-gutter':'.cm-lineNumbers'))throw Error('Breakpoint click missed gutter');target.dispatchEvent(new MouseEvent('mousedown',{bubbles:true,clientX:x,clientY:y,button:0}));await until(()=>!S.busy);await new Promise(r=>requestAnimationFrame(r));}
 await gutterClick(idleLine);checks.push({name:'Line-number click queues breakpoint before debugging and draws dot',ok:S.breakpoints.length===1&&!!$('.cm-breakpoint')});
 await gutterClick(idleLine,true);checks.push({name:'Left-margin click removes breakpoint and dot immediately',ok:S.breakpoints.length===0&&!$('.cm-breakpoint')});
 await gutterClick(idleLine,true);await startDebug();checks.push({name:'Starting debugger installs the selected breakpoint',ok:S.breakpoints.length===1&&Number.isInteger(S.breakpoints[0].id)});
 await debugAction('continue');await until(()=>S.debug==='paused'&&S.location.line===idleLine);checks.push({name:'Continue stops at breakpoint created by gutter click',ok:S.location.line===idleLine});
 await gutterClick(idleLine,true);await gutterClick(isrLine);checks.push({name:'Paused gutter click installs and draws ISR breakpoint',ok:S.breakpoints.length===1&&S.breakpoints[0].line===isrLine&&!!$('.cm-breakpoint')});
 panel('interrupts');checks.push({name:'Interrupt panel enabled in simulator',ok:!$('#triggerInterrupt').disabled});await api('triggerInterrupt',{source:'INT0'});await debugAction('continue');await until(()=>S.debug==='paused'&&S.location.line===isrLine);await debugAction('stepi');checks.push({name:'ISR executes through native UI workflow',ok:formatHex(S.values.irq_count)==='0x01'});
 view('files');panel('interrupts');renderInspector();$('#toast').hidden=true;if(S.location.line)E.go(S.location.line);await new Promise(r=>setTimeout(r,600));
 await api('uiTestDone',{checks,ok:checks.every(c=>c.ok),errors:[],registers:S.values,location:S.location});
 }catch(e){await api('uiTestDone',{checks,ok:false,error:e.message,stack:e.stack});}}
window.addEventListener('unhandledrejection',e=>toast(e.reason?.message||String(e.reason),true));
boot();
